import { StyleSheet } from "react-native";

export const colors = {
  redMain: "#7b0000",
  redTop: "#9c0000",
  redBottom: "#2b0000",
  white: "#fff",
  black: "#000",
  grayLight: "#f5f5f5",
  grayDark: "#333",
};

export const globalStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.grayLight,
    padding: 20,
  },
  homeWrap: {
    flex: 1,
    backgroundColor: colors.redMain,
  },
  homeContent: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  redTop: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: "55%",
    backgroundColor: colors.redTop,
  },
  redBottom: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: "50%",
    backgroundColor: colors.redBottom,
    borderTopLeftRadius: 45,
    borderTopRightRadius: 45,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 6,
  },
  title: {
    fontSize: 24,
    fontWeight: "800",
    color: colors.redMain,
    marginBottom: 20,
    textAlign: "center",
    letterSpacing: 0.5,
  },
  pixelTitle: {
    fontSize: 44,
    fontWeight: "900",
    color: colors.white,
    textAlign: "center",
    textShadowColor: "rgba(255,255,255,0.8)",
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 6,
    marginBottom: 25,
    letterSpacing: 2,
  },
  modalContainer: {
  flex: 1,
  justifyContent: 'center',
  alignItems: 'center',
  backgroundColor: 'rgba(0, 0, 0, 0.5)', // Fundo semi-transparente
  },
  modalContent: {
  backgroundColor: '#fff',
  padding: 20,
  borderRadius: 10,
  width: '80%',
  alignItems: 'center',
  },
  modalTitle: {
  fontSize: 18,
  fontWeight: 'bold',
  marginBottom: 10,
  },
  modalText: {
  fontSize: 16,
  marginBottom: 10,
  color: '#333',
  },
  modalButtonRow: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  width: '100%',
  marginTop: 20,
  },
  modalButton: {
  flex: 1,
  padding: 10,
  borderRadius: 5,
  alignItems: 'center',
  marginHorizontal: 5,
  },
  modalButtonText: {
  color: '#fff',
  fontSize: 16,
  fontWeight: 'bold',
  },
  botaoExcluir: {
  marginTop: 10,
  backgroundColor: '#cc0000',
  paddingVertical: 8,
  borderRadius: 8,
  alignItems: 'center',
  },
  textoHeD: {
  fontSize: 16,
  color: '#cc0000',
  fontWeight: '500',
  },
  textoSelecionado: {
  color: '#fff',
  fontWeight: 'bold',
  },
  botaoHorario: {
  width: 70,
  height: 50,
  justifyContent: 'center',
  alignItems: 'center',
  borderWidth: 1,
  borderColor: '#cc0000',
  borderRadius: 8,
  margin: 5,
  backgroundColor: '#fff',
  },
  botaoSelecionado: {
    backgroundColor: '#cc0000',
    color: '#fff',
    fontWeight: 'bold',
  },
  card: {
  backgroundColor: '#fff',
  padding: 15,
  borderRadius: 10,
  marginBottom: 10,
  width: '100%',
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.1,
  shadowRadius: 3,
  elevation: 2,
  },
  calendar: {
  borderRadius: 10,
  elevation: 2,
  marginBottom: 20,
  },
  button: {
    width: "85%",
    backgroundColor: colors.redTop,
    paddingVertical: 16,
    paddingHorizontal: 28,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 15,
    marginBottom: 60,
    alignSelf: "center",
    shadowColor: "#7b0000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 6,
  },
  buttonText: {
    color: colors.white,
    fontSize: 18,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 1.5,
  },
  btnPrimary: {
    width: "90%",
    backgroundColor: colors.redTop,
    paddingVertical: 20,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 25,
    marginBottom: 40,
    alignSelf: "center",
    shadowColor: "#9c0000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 7,
  },
  btnPrimaryText: {
    color: colors.white,
    fontSize: 19,
    fontWeight: "800",
    textTransform: "uppercase",
    letterSpacing: 2,
  },
  listItem: {
    width: "100%",
    backgroundColor: colors.white,
    padding: 18,
    borderRadius: 14,
    marginBottom: 14,
    borderLeftWidth: 6,
    borderLeftColor: colors.redTop,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 3,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: colors.redTop,
    marginBottom: 6,
  },
  listText: {
    fontSize: 16,
    color: colors.grayDark,
    lineHeight: 22,
  },
  emptyText: {
    textAlign: "center",
    fontSize: 16,
    color: "#999",
    marginTop: 30,
  },
  input: {
    width: "100%",
    backgroundColor: colors.white,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#ddd",
    fontSize: 16,
    marginBottom: 15,
  },
  link: {
    color: colors.redTop,
    fontSize: 15,
    fontWeight: "600",
    textDecorationLine: "underline",
  },
  logo: {
    width: 280,
    height: 280,
    marginVertical: 20,
    resizeMode: "contain",
  },
});
